argocd-k3s:
  argo:
    global:
      domain: argocd.k3s2.local
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        extraTls: []

    redis-ha:
      enabled: false
      haproxy:
        enabled: false
