apiVersion: v2
name: gitlab
description: Gitlab Helm chart configured by Ujstor
type: application
version: 1.0.3
appVersion: "17.6.1"

dependencies:
- name: gitlab
  version: 1.0.2
  repository: "https://ujstor.github.io/helm-charts-apps"
  alias: gitlab-k3s
