apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-metallb-operator-k3s5
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook-dependency: system-cilium
spec:
  destination:
    namespace: metallb
    server: https://api.k3s5.ujstor.dev:6443
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s5-test/helm/system/metallb-operator
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: metallb-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
