apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-external-secrets-k3s2
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  destination:
    namespace: external-secrets
    server: https://api.k3s2.ujstor.dev:6442
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s2-win/helm/system/external-secrets
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
