apiVersion: v2
name: metallb-operator
description: MetalLB operator Helm chart configured by Ujstor
type: application
version: 1.0.0
appVersion: "0.14.8"

dependencies:
- name: metallb-operator
  version: 1.0.0
  repository: "https://ujstor.github.io/helm-charts-system"
