apiVersion: v2
name: service-mesh-test-app
description: Service mesh test app Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: service-mesh-test-app
  version: 1.0.0
  repository: "https://ujstor.github.io/helm-charts-github-apps"
