apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-cluster-test-k3s5
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s5-test/helm/app-of-apps
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
