apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ops-cluster-bootstrap
  namespace: gitops
spec:
  description: Project for bootstrapping cluster infrastructure
  # Allow any repository
  sourceRepos:
    - '*'
  # Allow deployment to any namespace
  destinations:
    - namespace: '*'
      server: https://api.k3s5.ujstor.dev:6443
    - namespace: '*'
      server: https://api.k3s4.ujstor.dev:6444
    - namespace: '*'
      server: https://api.k3s3.ujstor.dev:6443
    - namespace: '*'
      server: https://api.k3s2.ujstor.dev:6442
    - namespace: '*'
      server: https://api.k3s1.ujstor.com:6443
    - namespace: '*'
      server: https://kubernetes.default.svc
  # Allow all cluster-scoped resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  # Allow all namespace-scoped resources
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
