---
- name: Update package lists
  ansible.builtin.command:
    cmd: apt-get -y update

- name: Upgrade all packages
  ansible.builtin.command:
    cmd: apt-get -y upgrade

- name: Install public AuthorizedKeysFile
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ public_key }}"

- name: Install required packages
  ansible.builtin.package:
    name: 
      - ufw
      - fail2ban
    state: present

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: allow


- name: Allow incoming traffic on specified ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 22
    - 2222
    - 2233
    - 2244
    - 2255
    - 2266
    - 80
    - 443
    - 6443
    - 25
    - 465
    - 587
    - 993

- name: Configure Fail2Ban
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: preserve

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Ensure no conflicting PermitRootLogin in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    state: absent

- name: SSH Hardening for root user
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      PermitRootLogin prohibit-password
      PasswordAuthentication no
      X11Forwarding no
      MaxAuthTries 2
      AllowTcpForwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  ignore_errors: yes

- name: Restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
  ignore_errors: yes
