apiVersion: v2
name: istiod
description: Istio control plane Helm Chart
type: application
version: 1.0.0
appVersion: "1.24.2"

dependencies:
- name: istiod
  version: 1.0.0
  repository: "https://ujstor.github.io/helm-charts-system"
