### Site metadata ###

site_name: k3s Single Node Multi Cluster
site_description: Docs
# site_url: http:/ujstor.github.io/k3s-single-node-multi-cluster-iac

repo_url: https://github.com/ujstor/k3s-single-node-multi-cluster-iac
edit_uri: edit/main/docs/docs

### Build settings ###

theme:
  name: material
  custom_dir: custom_theme/
  theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - toc.flow
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Quick Start:
    - Overview: quick-start/overview.md
    - Terrafrom: quick-start/terraform.md
    - Ansible: quick-start/ansible.md
    - Helm: quick-start/helm.md
  - k3s0-ops Components:
    - Mailserver: k3s0-ops-components/mailserver.md
  - Deployment logs:
    - Terraform: deployment-logs/terraform.md
    - Ansible: deployment-logs/ansible.md

extra:
    generator: false

copyright: Copyright &copy; 2025 Ujstor
