metrics-k3s4:
  prometheus-grafana:
    grafana:
      adminPassword: root
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - grafana.k3s4.local
        path: /
