---
- name: Server prep
  hosts: server
  gather_facts: true
  become: true
  roles:
    - role: common
  tasks:
    - name: Check for existing token
      ansible.builtin.stat:
        path: /var/lib/rancher/k3s/server/token
      register: token_file

    - name: Read existing token if present
      ansible.builtin.slurp:
        path: /var/lib/rancher/k3s/server/token
      register: existing_token
      when: token_file.stat.exists
      no_log: true

    - name: Generate random token if no existing token
      ansible.builtin.shell: |
        set -o pipefail
        openssl rand -base64 64 | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1
      args:
        executable: /bin/bash
      register: k3s_token_generated
      when: not token_file.stat.exists
      changed_when: false
      no_log: true

    - name: Set token fact
      ansible.builtin.set_fact:
        token: "{{ existing_token.content | b64decode if token_file.stat.exists else k3s_token_generated.stdout }}"
      no_log: true}"
      no_log: true

- name: Setup K3S server k3s0
  hosts: k3s0
  become: true
  roles:
    - role: k3s.orchestration.prereq
    - role: k3s.orchestration.k3s_server

- name: Setup K3S server k3s1
  hosts: k3s1
  become: true
  roles:
    - role: k3s.orchestration.prereq
    - role: k3s.orchestration.k3s_server

- name: Setup K3S server k3s2
  hosts: k3s2
  become: true
  roles:
    - role: k3s.orchestration.prereq
    - role: k3s.orchestration.k3s_server

- name: Fetch and configure kubeconfigs
  hosts: server
  become: true
  tasks:
    - name: Fetch kubeconfig file from remote server
      ansible.builtin.fetch:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: "./kubeconfig_k3s{{ inventory_hostname | regex_replace('.*k3s([0-9]).*', '\\1') }}"
        flat: true
    - name: Replace server IP in kubeconfig
      ansible.builtin.replace:
        path: "./kubeconfig_k3s{{ inventory_hostname | regex_replace('.*k3s([0-9]).*', '\\1') }}"
        regexp: 'server: https://127.0.0.1:6443'
        replace: "server: https://{{ hostvars[inventory_hostname].api_endpoint[0] }}:6443"
      delegate_to: localhost
