---
server:
  children:
    k3s0:
      hosts:
        api.k3s0.ujstor.com:
          api_endpoint: 
           - api.k3s0.ujstor.com
          k3s_control_node: true
          k3s_server_init_node: true
          server_group: "k3s0"
    k3s1:
      hosts:
        api.k3s1.ujstor.com:
          api_endpoint: 
           - api.k3s1.ujstor.com
          k3s_control_node: true
          k3s_server_init_node: true
          server_group: "k3s1"
    k3s2:
      hosts:
        ssh.k3s2.ujstor.dev:
          api_endpoint:
           - api.k3s2.ujstor.dev
           - api.k3s2.local
          k3s_control_node: true
          k3s_server_init_node: true
          server_group: "k3s2"
          ansible_user: ujstor
          ansible_port: 2222
    k3s3:
      hosts:
        ssh.k3s3.ujstor.dev:
          api_endpoint:
           - api.k3s3.ujstor.dev
           - api.k3s3.local
          k3s_control_node: true
          k3s_server_init_node: true
          server_group: "k3s3"
          ansible_user: ujstor
          ansible_port: 2233
    k3s4:
      hosts:
        ssh.k3s4.ujstor.dev:
          api_endpoint:
           - api.k3s4.ujstor.dev
           - api.k3s4.local
          k3s_control_node: true
          k3s_server_init_node: true
          server_group: "k3s4"
          ansible_user: ujstor
          ansible_port: 2244
    k3s5:
      hosts:
        api.k3s5.ujstor.dev:
          api_endpoint: 
           - api.k3s5.ujstor.dev
          k3s_control_node: true
          k3s_server_init_node: true
          server_group: "k3s5"
  vars:
    k3s_version: v1.31.3+k3s1
    extra_server_args: >-
      --cluster-cidr=10.255.0.0/16
      --service-cidr=10.254.0.0/16
      --disable servicelb
      --disable traefik
      --flannel-backend=none
      --egress-selector-mode=disabled
      --disable-cloud-controller
      --disable-helm-controller
      --disable-network-policy
      --disable-kube-proxy
      {% for san in api_endpoint %}
      --tls-san {{ san }}
      {% endfor %}
