apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-k3s0-harbor-backup-k3s4
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: k3s0-harbor-backup
    server: https://api.k3s4.ujstor.dev:6444
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s4-backup/helm/apps/k3s0-harbor-backup
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: k3s0-harbor-backup
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
